# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MVVM' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MVVM

  pod 'Alamofire'
  pod 'Moya'
  pod 'Moya/RxSwift'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Action'
  pod 'ObjectMapper'
  pod 'Moya/ReactiveSwift'
  pod 'RxDataSources'

  target 'MVVMTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MVVMUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
